parameters:
    jeka.yandex_yml.document.class: Jeka\YandexYMLBundle\YandexYML\Document
    jeka.yandex_yml.shop_name: Test shop name
    jeka.yandex_yml.shop_company: Test company LTD
    jeka.yandex_yml.shop_url: https://github.com/jekill/JekaYandexYMLBundle

services:
    jeka.yandex_yml.document:
        class: %jeka.yandex_yml.document.class%
        arguments: [%jeka.yandex_yml.shop_name%, %jeka.yandex_yml.shop_company%, %jeka.yandex_yml.shop_url%]
